import { writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import { BARS, b, cue } from "../src/videos/verifai-loop/cues";

/** Writes the beat sheet the product owner reads, from cues.ts (the single source). */
const rows: [number, string][] = [
  [1, "Opening. The Verifai mark draws itself (hex, then check, then fill); the wordmark lands on sixteenths."],
  [2, "Punchline: \"Every part. / Every rule.\" One word per beat."],
  [3, "App window in. Cursor glides to Run check and clicks on beat 4; the button shows Checking at the same width."],
  [4, "Rules resolve one per beat: pass, pass, pass, fail (HOLE-04: 2.5 mm)."],
  [5, "Pass, warning. Counters update. Cursor clicks the failed rule on beat 4."],
  [6, "Magic move: the fail mark travels into the detail panel header. Facts on eighths, the suggested fix word by word."],
  [7, "Apply fix on beat 2, Applying, then the mark turns to pass on beat 3: 5 passed, 0 failed."],
  [8, "Punchline: \"Compliance at a glance.\""],
  [9, "Compliance report. Score counts to 96%, category bars start filling on beats 3 and 4."],
  [10, "Bars fill on beats 1 and 2; Export PDF clicked on beat 3, Exported on beat 4."],
  [11, "Release route. Send to approval on beat 2; design review waits for a person."],
  [12, "Design lead approves on beat 1; release on beat 3: lifecycle chip In work to Released (strongest moment)."],
  [13, "Punchline: \"Verified before release.\""],
  [14, "Logo lockup draws again."],
  [15, "Loop: the wordmark blurs out, the mark un-draws, back to the empty first frame."],
];
const fmt = (s: number) => s.toFixed(2).padStart(5, "0");
let md = `# Verifai loop: beat sheet\n\nGenerated by \`bun scripts/beat-sheet.ts\` from \`src/videos/verifai-loop/cues.ts\`. 120 BPM, 4/4, ${BARS} bars, ${b(BARS + 1)} s, silent.\n\n| Bar | Time | Frame (60 fps) | What happens |\n|---|---|---|---|\n`;
for (const [bar, text] of rows) md += `| ${bar} | ${fmt(b(bar))}–${fmt(b(bar + 1))} s | ${Math.round(b(bar) * 60)} | ${text} |\n`;
md += `\nKey cues: run click ${cue.run.click} s, fail result ${cue.rules[3]} s, apply ${cue.detail.apply} s, released ${cue.route.released} s.\n`;
writeFileSync(join(resolve(import.meta.dirname, ".."), "beat-sheet.md"), md);
console.log(md);
