import { writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import { BARS, b, cue } from "../src/videos/verifai-loop/cues";

/** Writes the beat sheet the product owner reads, from cues.ts (the single source). */
const rows: [number, string][] = [
  [1, "Opening. The mark's corner blocks close in from the frame's corners like a viewfinder, the check draws, the wordmark lands."],
  [2, "Punchline: \"Every drawing. / Every 3D model.\" with its dimension: CA-00001445."],
  [3, "Intake: the Approve route task for CA-00001445 is picked up; the CATIA worker opens 1011548. The part turns as a wireframe."],
  [4, "A section plane passes through the part: bodies 1, hidden bodies 0, visible sketches 0, iso capture."],
  [5, "$ verifai inspect 1011548 --rev A. The reading band sweeps the sheet; rules 1 and 2 pass."],
  [6, "The camera pushes in and locks on each failure: general tolerance standard, then title block approvals."],
  [7, "Pull back to the whole sheet; rules 7 and 8; AUTHORITY: 6 pass, 2 major."],
  [8, "Punchline: \"Checked in minutes.\" with its dimension: 140 s per Change Action (benchmark)."],
  [9, "Inspection report: PASSED 35 / FAILED 12 count up, the Change Action contents fill in."],
  [10, "~ ISSUES FOUND, action items; on beat 4 the page folds into the route task's PDF attachment."],
  [11, "Route task: VerifAI's pre-check comment and the report; the engineer's cursor comes in."],
  [12, "The engineer rejects; the task is returned to the designer."],
  [13, "Punchline: \"Caught before / production.\" with its dimension: before release."],
  [14, "VerifAI lockup, then \"by MetaPLM\"."],
  [15, "Loop: the corner blocks fly back out to the frame's corners and fade; the bare grid of frame 0."],
];
const fmt = (s: number) => s.toFixed(2).padStart(5, "0");
let md = `# VerifAI loop: beat sheet\n\nGenerated by \`bun scripts/beat-sheet.ts\` from \`src/videos/verifai-loop/cues.ts\`. 120 BPM, 4/4, ${BARS} bars, ${b(BARS + 1)} s, silent.\n\n| Bar | Time | Frame (60 fps) | What happens |\n|---|---|---|---|\n`;
for (const [bar, text] of rows) md += `| ${bar} | ${fmt(b(bar))}–${fmt(b(bar + 1))} s | ${Math.round(b(bar) * 60)} | ${text} |\n`;
md += `
Key cues: pickup ${cue.model.lines[2]} s, first finding ${cue.inspect.rules[0]} s, report fold ${cue.report.shrink} s, reject ${cue.task.reject} s.
`;
writeFileSync(join(resolve(import.meta.dirname, ".."), "beat-sheet.md"), md);
console.log(md);
