import { writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

import { BARS, b, cue } from "../src/videos/verifai-loop/cues";

/** Writes the beat sheet the product owner reads, from cues.ts (the single source). */
const rows: [number, string][] = [
  [1, "Opening. The VerifAI mark's four corner blocks snap in, the check draws, the wordmark lands."],
  [2, "Punchline: \"Every drawing. / Every 3D model.\""],
  [3, "Change Action CA-00001445: 3 physical products arrive, the Approve route task starts, VerifAI picks it up."],
  [4, "Products are queued for VerifAI, one per beat."],
  [5, "Drawing 1011548 Rev A: the reading band sweeps the sheet; rules 1 and 2 resolve."],
  [6, "Rules 3 to 6 resolve; markers land on the sheet (General tolerance and Title block approvals fail)."],
  [7, "Rules 7 and 8; Authority: 2 major findings, report ready."],
  [8, "Punchline: \"Checked in minutes.\""],
  [9, "Inspection report: PASSED 35 / FAILED 12 count up, the Change Action contents fill in."],
  [10, "~ ISSUES FOUND, action items; on beat 4 the page folds into the route task's PDF attachment."],
  [11, "Route task: VerifAI's pre-check comment and the report; the engineer's cursor comes in."],
  [12, "The engineer rejects; the task is returned to the designer."],
  [13, "Punchline: \"Caught before / production.\""],
  [14, "VerifAI lockup, then \"by MetaPLM\"."],
  [15, "Loop: everything folds back to the empty first frame."],
];
const fmt = (s: number) => s.toFixed(2).padStart(5, "0");
let md = `# VerifAI loop: beat sheet\n\nGenerated by \`bun scripts/beat-sheet.ts\` from \`src/videos/verifai-loop/cues.ts\`. 120 BPM, 4/4, ${BARS} bars, ${b(BARS + 1)} s, silent.\n\n| Bar | Time | Frame (60 fps) | What happens |\n|---|---|---|---|\n`;
for (const [bar, text] of rows) md += `| ${bar} | ${fmt(b(bar))}–${fmt(b(bar + 1))} s | ${Math.round(b(bar) * 60)} | ${text} |\n`;
md += `
Key cues: pickup ${cue.ca.pickup} s, first finding ${cue.inspect.rules[0]} s, report fold ${cue.report.shrink} s, reject ${cue.task.reject} s.
`;
writeFileSync(join(resolve(import.meta.dirname, ".."), "beat-sheet.md"), md);
console.log(md);
